name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*@harmonic*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Test Release Version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Build Shaka Player
        run: python build/all.py

      - name: Zip release files
        run: zip shaka-player-${{ env.RELEASE_VERSION }}.zip shaka-player.compiled.debug.js  shaka-player.ui.debug.js controls.css  shaka-player.compiled.js        shaka-player.ui.js
        working-directory: dist

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/shaka-player-${{ env.RELEASE_VERSION }}.zip
          asset_name: shaka-player-${{ env.RELEASE_VERSION }}.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"